#!/usr/bin/env npx ts-node --esm
/**
 * Generate a markdown trend table from all historical baselines.
 *
 * Usage:
 *   npx ts-node --esm scripts/trend-report.ts [--output <path>]
 *
 * Reads all *.json files in baselines/ (excluding schema.json) in chronological order
 * and renders a table showing how each metric has changed over time.
 */

import { readFileSync, writeFileSync, readdirSync, existsSync } from "fs";
import { resolve, join } from "path";
import type { MetricSnapshot } from "../src/harness/types.js";

function loadAll(dir: string): MetricSnapshot[] {
  const absDir = resolve(dir);
  if (!existsSync(absDir)) {
    throw new Error(`Baselines directory not found: ${absDir}`);
  }

  const files = readdirSync(absDir)
    .filter((f) => f.endsWith(".json") && f !== "schema.json" && f !== "latest.json")
    .sort(); // lexicographic = chronological for ISO-date filenames

  const snapshots: MetricSnapshot[] = files.map((f) => {
    const content = readFileSync(join(absDir, f), "utf-8");
    return JSON.parse(content) as MetricSnapshot;
  });

  // Also include latest.json if it exists and isn't duplicated
  const latestPath = join(absDir, "latest.json");
  if (existsSync(latestPath)) {
    const latest = JSON.parse(readFileSync(latestPath, "utf-8")) as MetricSnapshot;
    const alreadyIncluded = snapshots.some((s) => s.capturedAt === latest.capturedAt);
    if (!alreadyIncluded) {
      snapshots.push(latest);
    }
  }

  return snapshots.sort(
    (a, b) => new Date(a.capturedAt).getTime() - new Date(b.capturedAt).getTime()
  );
}

function pctChange(base: number, current: number): string {
  if (base === 0) return "—";
  const change = ((current - base) / base) * 100;
  const sign = change >= 0 ? "+" : "";
  return `${sign}${change.toFixed(1)}%`;
}

function severity(base: number, current: number): string {
  if (base === 0) return "";
  const change = Math.abs(((current - base) / base) * 100);
  if (change < 5) return "⚪";
  if (change < 10) return "🟡";
  return "🔴";
}

function generateTrendReport(snapshots: MetricSnapshot[]): string {
  if (snapshots.length === 0) {
    return "# Trend Report\n\nNo baseline snapshots found in `baselines/`.\n";
  }

  const lines: string[] = [];
  lines.push("# CLI Wrapper Monitor — Trend Report");
  lines.push("");
  lines.push(`_${snapshots.length} snapshot(s) analyzed_`);
  lines.push("");

  if (snapshots.length === 1) {
    lines.push(
      "> **Only one snapshot available.** Run another snapshot next month to see trends."
    );
    lines.push("");
  }

  // Collect all experiment + metric combos from first snapshot
  const first = snapshots[0];
  const dates = snapshots.map((s) => new Date(s.capturedAt).toISOString().slice(0, 10));

  for (const [expName, exp] of Object.entries(first.experiments)) {
    lines.push(`## ${expName}`);
    lines.push("");

    for (const [metricKey, baseMetric] of Object.entries(exp.metrics)) {
      lines.push(`### ${metricKey}`);
      lines.push("");
      lines.push(`_${baseMetric.description}_`);
      lines.push("");

      // Header row
      const headerCols = ["Date", "Value", "vs First", ""];
      lines.push(`| ${headerCols.join(" | ")} |`);
      lines.push(`|${headerCols.map(() => "---").join("|")}|`);

      for (let i = 0; i < snapshots.length; i++) {
        const snap = snapshots[i];
        const currExp = snap.experiments[expName];
        const currMetric = currExp?.metrics[metricKey];

        if (!currMetric) {
          lines.push(`| ${dates[i]} | — | — | ⚠️ |`);
          continue;
        }

        const vsFirst =
          i === 0 ? "baseline" : pctChange(baseMetric.value, currMetric.value);
        const sev = i === 0 ? "" : severity(baseMetric.value, currMetric.value);

        lines.push(
          `| ${dates[i]} | ${currMetric.value.toLocaleString()} ${currMetric.unit} | ${vsFirst} | ${sev} |`
        );
      }

      lines.push("");
    }
  }

  // Regression summary
  lines.push("## Regression Thresholds");
  lines.push("");
  lines.push("| Severity | Threshold |");
  lines.push("|----------|-----------|");
  lines.push("| ⚪ Info | < 5% change |");
  lines.push("| 🟡 Warning | 5–10% change |");
  lines.push("| 🔴 Regression | > 10% change |");
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push(
    "*Generated by [cli-wrapper-monitor](https://github.com/copilot-autogent/cli-wrapper-monitor)*"
  );

  return lines.join("\n");
}

function main(): void {
  const args = process.argv.slice(2);
  let output: string | null = null;
  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--output" && args[i + 1]) output = args[++i];
  }

  const snapshots = loadAll("baselines");
  const report = generateTrendReport(snapshots);

  if (output) {
    writeFileSync(resolve(output), report, "utf-8");
    console.log(`Trend report written to: ${output}`);
  } else {
    console.log(report);
  }
}

main();
